import ebnf.{
  Alternative, NonTerminal, Optional, Production, Repetition, Sequence, Terminal,
  UnexpectedEnd,
}

import gleeunit
import gleeunit/should
import simplifile

pub fn main() -> Nil {
  gleeunit.main()
}

pub fn sample_empty_test() {
  let s = ""
  case ebnf.parse(s) {
    Ok(_) -> should.fail()
    Error(e) -> should.equal(e, UnexpectedEnd("nonterminal"))
  }
}

pub fn sample_one_test() {
  let assert Ok(content) = simplifile.read("test/sample1.ebnf")
  case ebnf.parse(content) {
    Ok(ast) -> {
      let res = [
        Production(
          "expression",
          Sequence([
            NonTerminal("term"),
            Repetition(
              Sequence([
                Alternative([Terminal("+"), Terminal("-")]),
                NonTerminal("term"),
              ]),
            ),
          ]),
          True,
        ),
        Production(
          "term",
          Sequence([
            NonTerminal("factor"),
            Repetition(
              Sequence([
                Alternative([Terminal("*"), Terminal("/")]),
                NonTerminal("factor"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "factor",
          Alternative([
            NonTerminal("number"),
            NonTerminal("variable"),
            Sequence([Terminal("("), NonTerminal("expression"), Terminal(")")]),
          ]),
          False,
        ),
        Production(
          "variable",
          Alternative([Terminal("x"), Terminal("y"), Terminal("z")]),
          False,
        ),
        Production(
          "number",
          Sequence([NonTerminal("digit"), Repetition(NonTerminal("digit"))]),
          False,
        ),
        Production(
          "digit",
          Alternative([
            Terminal("0"),
            Terminal("1"),
            Terminal("2"),
            Terminal("3"),
            Terminal("4"),
            Terminal("5"),
            Terminal("6"),
            Terminal("7"),
            Terminal("8"),
            Terminal("9"),
          ]),
          False,
        ),
      ]
      should.equal(ast, res)
    }
    Error(_e) -> {
      should.fail()
    }
  }
}

pub fn sample_two_test() {
  let assert Ok(content) = simplifile.read("test/sample2.ebnf")
  case ebnf.parse(content) {
    Ok(ast) -> {
      should.equal(ast, [
        Production(
          "module",
          Sequence([
            Terminal("MODULE"),
            NonTerminal("ident"),
            Terminal(";"),
            NonTerminal("importList"),
            NonTerminal("declSeq"),
            NonTerminal("beginBlock"),
            Terminal("END"),
            NonTerminal("ident"),
            Terminal("."),
          ]),
          True,
        ),
        Production(
          "importList",
          Optional(
            Sequence([Terminal("IMPORT"), NonTerminal("modList"), Terminal(";")]),
          ),
          False,
        ),
        Production(
          "modName",
          Alternative([
            NonTerminal("ident"),
            Sequence([
              NonTerminal("ident"),
              Terminal(":="),
              NonTerminal("ident"),
            ]),
          ]),
          False,
        ),
        Production(
          "modList",
          Alternative([
            NonTerminal("modName"),
            Sequence([
              NonTerminal("modList"),
              Terminal(","),
              NonTerminal("modName"),
            ]),
          ]),
          False,
        ),
        Production(
          "beginBlock",
          Optional(Sequence([Terminal("BEGIN"), NonTerminal("statementSeq")])),
          False,
        ),
        Production(
          "ident",
          Sequence([NonTerminal("letter"), Repetition(NonTerminal("letter"))]),
          False,
        ),
        Production(
          "identList",
          Alternative([
            NonTerminal("identDef"),
            Sequence([
              NonTerminal("identList"),
              Terminal(","),
              NonTerminal("identDef"),
            ]),
          ]),
          False,
        ),
        Production(
          "qualident",
          Alternative([
            NonTerminal("ident"),
            Sequence([NonTerminal("ident"), Terminal("."), NonTerminal("ident")]),
          ]),
          False,
        ),
        Production(
          "designator",
          Alternative([
            NonTerminal("qualident"),
            Sequence([
              NonTerminal("designator"),
              Terminal("."),
              NonTerminal("ident"),
            ]),
            Sequence([
              NonTerminal("designator"),
              Terminal("["),
              NonTerminal("exprList"),
              Terminal("]"),
            ]),
            Sequence([NonTerminal("designator"), Terminal("^")]),
            Sequence([
              NonTerminal("designator"),
              Terminal("("),
              NonTerminal("qualident"),
              Terminal(")"),
            ]),
          ]),
          False,
        ),
        Production(
          "identDef",
          Alternative([
            NonTerminal("ident"),
            Sequence([NonTerminal("ident"), Terminal("*")]),
            Sequence([NonTerminal("ident"), Terminal("-")]),
          ]),
          False,
        ),
        Production(
          "declSeq",
          Sequence([NonTerminal("declSeqList"), NonTerminal("procDecls")]),
          False,
        ),
        Production(
          "declSeqList",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("declSeqList"),
                Terminal("CONST"),
                NonTerminal("constDeclList"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("declSeqList"),
                Terminal("TYPE"),
                NonTerminal("typeDeclList"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("declSeqList"),
                Terminal("VAR"),
                NonTerminal("varDeclList"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "constDeclList",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("identDef"),
                Terminal("="),
                NonTerminal("constExpr"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("constDeclList"),
                Terminal(";"),
                NonTerminal("identDef"),
                Terminal("="),
                NonTerminal("constExpr"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "typeDeclList",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("identDef"),
                Terminal("="),
                NonTerminal("type"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("typeDeclList"),
                Terminal(";"),
                NonTerminal("identDef"),
                Terminal("="),
                NonTerminal("type"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "varDeclList",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("identList"),
                Terminal(":"),
                NonTerminal("type"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("varDeclList"),
                Terminal(";"),
                NonTerminal("identList"),
                Terminal("="),
                NonTerminal("type"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "procDecls",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("procDecls"),
                NonTerminal("procDecl"),
                Terminal(";"),
              ]),
            ),
            Optional(
              Sequence([NonTerminal("procDecls"), NonTerminal("forwardDecl")]),
            ),
          ]),
          False,
        ),
        Production(
          "procDecl",
          Sequence([
            Terminal("PROCEDURE"),
            NonTerminal("receiver"),
            NonTerminal("identDef"),
            NonTerminal("formalPars"),
            Terminal(";"),
            NonTerminal("declSeq"),
            NonTerminal("beginBlock"),
            Terminal("END"),
            NonTerminal("ident"),
          ]),
          False,
        ),
        Production(
          "forwardDecl",
          Sequence([
            Terminal("PROCEDURE"),
            Terminal("^"),
            NonTerminal("receiver"),
            NonTerminal("identDef"),
            NonTerminal("formalPars"),
            Terminal(";"),
          ]),
          False,
        ),
        Production(
          "receiver",
          Optional(
            Sequence([
              Terminal("("),
              NonTerminal("byReference"),
              NonTerminal("ident"),
              Terminal(":"),
              NonTerminal("ident"),
              Terminal(")"),
            ]),
          ),
          False,
        ),
        Production(
          "formalPars",
          Sequence([
            Terminal("("),
            NonTerminal("fpSectionList"),
            Terminal(")"),
            NonTerminal("retType"),
          ]),
          False,
        ),
        Production(
          "retType",
          Optional(Sequence([Terminal(":"), NonTerminal("qualident")])),
          False,
        ),
        Production(
          "fpSectionList",
          Sequence([
            NonTerminal("byReference"),
            NonTerminal("identList"),
            Terminal(":"),
            NonTerminal("type"),
          ]),
          False,
        ),
        Production("byReference", Optional(Terminal("VAR")), False),
        Production(
          "type",
          Alternative([
            NonTerminal("qualident"),
            Sequence([
              Terminal("ARRAY"),
              NonTerminal("constExprList"),
              Terminal("OF"),
              NonTerminal("type"),
            ]),
            Sequence([
              Terminal("RECORD"),
              NonTerminal("baseRec"),
              NonTerminal("fieldList"),
              Terminal("END"),
            ]),
            Sequence([Terminal("POINTER"), Terminal("TO"), NonTerminal("type")]),
            Sequence([Terminal("PROCEDURE"), NonTerminal("formalPars")]),
          ]),
          False,
        ),
        Production(
          "constExprList",
          Alternative([
            NonTerminal("constExpr"),
            Sequence([
              NonTerminal("constExprList"),
              Terminal(","),
              NonTerminal("constExpr"),
            ]),
          ]),
          False,
        ),
        Production(
          "baseRec",
          Optional(
            Sequence([Terminal("("), NonTerminal("qualident"), Terminal(")")]),
          ),
          False,
        ),
        Production(
          "fieldList",
          Alternative([
            Optional(
              Sequence([
                NonTerminal("identList"),
                Terminal(":"),
                NonTerminal("type"),
              ]),
            ),
            Optional(
              Sequence([
                NonTerminal("fieldList"),
                Terminal(";"),
                NonTerminal("identList"),
                Terminal(":"),
                NonTerminal("type"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "statementSeq",
          Alternative([
            NonTerminal("statement"),
            Sequence([
              NonTerminal("statementSeq"),
              Terminal(";"),
              NonTerminal("statement"),
            ]),
          ]),
          False,
        ),
        Production(
          "statement",
          Alternative([
            Sequence([
              NonTerminal("designator"),
              Terminal(":="),
              NonTerminal("expr"),
            ]),
            Sequence([NonTerminal("designator"), NonTerminal("params")]),
            Sequence([
              Terminal("IF"),
              NonTerminal("expr"),
              Terminal("THEN"),
              NonTerminal("statementSeq"),
              NonTerminal("elsifList"),
              NonTerminal("elsePart"),
              Terminal("END"),
            ]),
            Sequence([
              Terminal("CASE"),
              NonTerminal("expr"),
              Terminal("OF"),
              NonTerminal("caseList"),
              NonTerminal("elsePart"),
              Terminal("END"),
            ]),
            Sequence([
              Terminal("WHILE"),
              NonTerminal("expr"),
              Terminal("DO"),
              NonTerminal("statementSeq"),
              Terminal("END"),
            ]),
            Sequence([
              Terminal("REPEAT"),
              NonTerminal("statementSeq"),
              Terminal("UNTIL"),
              NonTerminal("expr"),
            ]),
            Sequence([
              Terminal("FOR"),
              NonTerminal("ident"),
              Terminal(":="),
              NonTerminal("expr"),
              Terminal("TO"),
              NonTerminal("expr"),
              NonTerminal("byStep"),
              Terminal("DO"),
              NonTerminal("statementSeq"),
              Terminal("END"),
            ]),
            Sequence([
              Terminal("LOOP"),
              NonTerminal("statementSeq"),
              Terminal("END"),
            ]),
            Sequence([
              Terminal("WITH"),
              NonTerminal("guardList"),
              NonTerminal("elsePart"),
              Terminal("END"),
            ]),
            Terminal("EXIT"),
            Sequence([Terminal("RETURN"), NonTerminal("exprOpt")]),
          ]),
          False,
        ),
        Production(
          "params",
          Optional(
            Sequence([Terminal("("), NonTerminal("exprList"), Terminal(")")]),
          ),
          False,
        ),
        Production(
          "elsifList",
          Optional(
            Sequence([
              NonTerminal("elsifList"),
              Terminal("ELSIF"),
              NonTerminal("expr"),
              Terminal("THEN"),
              NonTerminal("statementSeq"),
            ]),
          ),
          False,
        ),
        Production(
          "elsePart",
          Optional(Sequence([Terminal("ELSE"), NonTerminal("statementSeq")])),
          False,
        ),
        Production(
          "caseList",
          Optional(
            Sequence([
              NonTerminal("caseLabelsList"),
              Terminal(":"),
              NonTerminal("statementSeq"),
            ]),
          ),
          False,
        ),
        Production(
          "caseLabelsList",
          Alternative([
            NonTerminal("caseLabels"),
            Sequence([
              NonTerminal("caseLabelsList"),
              Terminal(","),
              NonTerminal("caseLabels"),
            ]),
          ]),
          False,
        ),
        Production(
          "caseLabels",
          Alternative([
            NonTerminal("constExpr"),
            Sequence([
              NonTerminal("constExpr"),
              Terminal(".."),
              NonTerminal("constExpr"),
            ]),
          ]),
          False,
        ),
        Production(
          "byStep",
          Optional(Sequence([Terminal("BY"), NonTerminal("constExpr")])),
          False,
        ),
        Production(
          "guardList",
          Alternative([
            Sequence([
              NonTerminal("guard"),
              Terminal("DO"),
              NonTerminal("statementSeq"),
            ]),
            Sequence([
              NonTerminal("guardList"),
              Terminal("|"),
              NonTerminal("guard"),
              Terminal("DO"),
              NonTerminal("statementSeq"),
            ]),
          ]),
          False,
        ),
        Production(
          "guard",
          Sequence([
            NonTerminal("qualident"),
            Terminal(":"),
            NonTerminal("qualident"),
          ]),
          False,
        ),
        Production("exprOpt", Optional(NonTerminal("expr")), False),
        Production("constExpr", NonTerminal("expr"), False),
        Production(
          "expr",
          Alternative([
            NonTerminal("simpleExpr"),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("="),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("#"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("<"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("<="),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal(">"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal(">="),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("IN"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("IS"),
              NonTerminal("simpleExpr"),
            ]),
          ]),
          False,
        ),
        Production(
          "simpleExpr",
          Alternative([
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("+"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("-"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("*"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("/"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("DIV"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("MOD"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("OR"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([
              NonTerminal("simpleExpr"),
              Terminal("&"),
              NonTerminal("simpleExpr"),
            ]),
            Sequence([Terminal("("), NonTerminal("simpleExpr"), Terminal(")")]),
            Sequence([NonTerminal("designator"), NonTerminal("params")]),
            NonTerminal("number"),
            NonTerminal("CHARCONST"),
            NonTerminal("STRCONST"),
            Terminal("NIL"),
            NonTerminal("Set"),
            Sequence([Terminal("~"), NonTerminal("simpleExpr")]),
          ]),
          False,
        ),
        Production(
          "number",
          Alternative([
            NonTerminal("INTCONST"),
            NonTerminal("REALCONST"),
            NonTerminal("LREALCONST"),
          ]),
          False,
        ),
        Production(
          "exprList",
          Alternative([
            NonTerminal("expr"),
            Sequence([
              NonTerminal("exprList"),
              Terminal(","),
              NonTerminal("expr"),
            ]),
          ]),
          False,
        ),
        Production(
          "Set",
          Sequence([Terminal("{"), NonTerminal("elementList"), Terminal("}")]),
          False,
        ),
        Production(
          "elementList",
          Alternative([
            Optional(NonTerminal("element")),
            Optional(
              Sequence([
                NonTerminal("elementList"),
                Terminal(","),
                NonTerminal("element"),
              ]),
            ),
          ]),
          False,
        ),
        Production(
          "element",
          Alternative([
            NonTerminal("expr"),
            Sequence([NonTerminal("expr"), Terminal(".."), NonTerminal("expr")]),
          ]),
          False,
        ),
        Production(
          "digit",
          Alternative([
            Terminal("0"),
            Terminal("1"),
            Terminal("2"),
            Terminal("3"),
            Terminal("4"),
            Terminal("5"),
            Terminal("6"),
            Terminal("7"),
            Terminal("8"),
            Terminal("9"),
          ]),
          False,
        ),
        Production(
          "digits",
          Sequence([NonTerminal("digit"), Repetition(NonTerminal("digit"))]),
          False,
        ),
        Production(
          "hexDigit",
          Alternative([
            NonTerminal("digit"),
            Terminal("A"),
            Terminal("B"),
            Terminal("C"),
            Terminal("D"),
            Terminal("E"),
            Terminal("F"),
          ]),
          False,
        ),
        Production(
          "hexDigits",
          Sequence([
            NonTerminal("hexDigit"),
            Repetition(NonTerminal("hexDigit")),
          ]),
          False,
        ),
        Production(
          "letter",
          Alternative([
            Terminal("A"),
            Terminal("B"),
            Terminal("C"),
            Terminal("D"),
            Terminal("E"),
            Terminal("F"),
            Terminal("G"),
            Terminal("H"),
            Terminal("I"),
            Terminal("J"),
            Terminal("K"),
            Terminal("L"),
            Terminal("M"),
            Terminal("N"),
            Terminal("O"),
            Terminal("P"),
            Terminal("Q"),
            Terminal("R"),
            Terminal("S"),
            Terminal("T"),
            Terminal("U"),
            Terminal("V"),
            Terminal("W"),
            Terminal("X"),
            Terminal("Y"),
            Terminal("Z"),
            Terminal("a"),
            Terminal("b"),
            Terminal("c"),
            Terminal("d"),
            Terminal("e"),
            Terminal("f"),
            Terminal("g"),
            Terminal("h"),
            Terminal("i"),
            Terminal("j"),
            Terminal("k"),
            Terminal("l"),
            Terminal("m"),
            Terminal("n"),
            Terminal("o"),
            Terminal("p"),
            Terminal("q"),
            Terminal("r"),
            Terminal("s"),
            Terminal("t"),
            Terminal("u"),
            Terminal("v"),
            Terminal("w"),
            Terminal("x"),
            Terminal("y"),
            Terminal("z"),
          ]),
          False,
        ),
        Production(
          "INTCONST",
          Alternative([
            NonTerminal("digits"),
            Sequence([
              NonTerminal("digit"),
              NonTerminal("hexDigits"),
              Terminal("H"),
            ]),
          ]),
          False,
        ),
        Production(
          "CHARCONST",
          Sequence([
            NonTerminal("digit"),
            NonTerminal("hexDigits"),
            Terminal("X"),
          ]),
          False,
        ),
        Production(
          "STRCONST",
          Sequence([
            Terminal("\""),
            Repetition(
              Alternative([NonTerminal("letter"), NonTerminal("digit")]),
            ),
            Terminal("\""),
          ]),
          False,
        ),
        Production(
          "REALCONST",
          Sequence([
            NonTerminal("digits"),
            Terminal("."),
            Repetition(NonTerminal("digit")),
            Terminal("E"),
            Optional(NonTerminal("exponent_part")),
          ]),
          False,
        ),
        Production(
          "LREALCONST",
          Sequence([
            NonTerminal("digits"),
            Terminal("."),
            Repetition(NonTerminal("digit")),
            Terminal("D"),
            Optional(NonTerminal("exponent_part")),
          ]),
          False,
        ),
        Production(
          "exponent_part",
          Sequence([
            Optional(Alternative([Terminal("+"), Terminal("-")])),
            NonTerminal("digits"),
          ]),
          False,
        ),
      ])
    }
    Error(_) -> {
      should.fail()
    }
  }
}
